---
- name: Run automated tests on server
  hosts: "{{ server }}"
  become: yes
  vars:
    test_dir: "/opt/job_repo/tests"
    test_type: "{{ test_type }}" # Options: pytest, perl

  tasks:
    - name: Ensure testing dependencies are installed (Python)
      pip:
        name: pytest
        state: present
      when: test_type == "pytest"

    - name: Ensure Perl testing dependencies are installed
      apt:
        name: libtest-simple-perl
        state: present
      when: ansible_os_family == "Debian" and test_type == "perl"

    - name: Run Python tests with PyTest
      shell: "pytest {{ test_dir }} --maxfail=1 --disable-warnings"
      when: test_type == "pytest"
      register: pytest_result

    - name: Run Perl tests
      shell: "prove {{ test_dir }}"
      when: test_type == "perl"
      register: perltest_result

    - name: Display Python test results
      debug:
        var: pytest_result.stdout
      when: test_type == "pytest"

    - name: Display Perl test results
      debug:
        var: perltest_result.stdout
      when: test_type == "perl"
