---
- name: Deploy and execute job on server
  hosts: "{{ server }}"
  become: yes
  vars:
    repo_url: "{{ repo_url }}"
    branch: "{{ branch }}"
    script_name: "{{ script_name }}"

  tasks:
    - name: Ensure Git is installed on Debian/Ubuntu
      apt:
        name: git
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Git is installed on RedHat/CentOS
      yum:
        name: git
        state: present
      when: ansible_os_family == "RedHat"

    - name: Clone or update the Git repository
      git:
        repo: "{{ repo_url }}"
        dest: /opt/job_repo
        version: "{{ branch }}"
        force: yes

    - name: Execute the job script
      shell: "perl /opt/job_repo/{{ script_name }}"
      args:
        creates: "/tmp/{{ script_name }}.log"

    - name: Verify execution
      shell: "cat /tmp/{{ script_name }}.log"
      register: job_output

    - name: Display job output
      debug:
        var: job_output.stdout
