---
- name: Query installed applications on server
  hosts: "{{ server }}"
  become: yes

  tasks:
    - name: Query installed packages on Debian/Ubuntu
      shell: "dpkg --list"
      when: ansible_os_family == "Debian"
      register: deb_packages

    - name: Query installed packages on RedHat/CentOS
      shell: "yum list installed"
      when: ansible_os_family == "RedHat"
      register: rhel_packages

    - name: Display Debian/Ubuntu packages
      debug:
        var: deb_packages.stdout
      when: ansible_os_family == "Debian"

    - name: Display RedHat/CentOS packages
      debug:
        var: rhel_packages.stdout
      when: ansible_os_family == "RedHat"
